Task4
NikoraDmytro/Team_Project_2023 pull request #2
Opened 2023-03-24 14:30 UTC by ira-bibik

Форма без заповнених полів
![image](https://user-images.githubusercontent.com/114294333/227553382-23fd26a3-7191-4ef8-8039-c1188ec20440.png)
Форма з правильно заповненими полями
![image](https://user-images.githubusercontent.com/114294333/227553175-77c1a661-cdc7-4f27-a5cc-3fcdfd398d7b.png)
Форма з неправильно заповненими полями
![image](https://user-images.githubusercontent.com/114294333/227553554-e66d94df-be8b-4242-9971-f114487ecfa5.png)

2023-03-24 15:42 UTC, NikoraDmytro requested changes

2023-03-24 15:42 UTC, NikoraDmytro commented on client/src/components/RegistrationForm/RegistrationForm.css
> +.additional-buttons .google-button {
Use .scss extention for this file instead of .css.
Thus you can use nesting like this:
.additional-buttons {
  .google-button { ... }
}

2023-03-24 15:42 UTC, NikoraDmytro commented on client/src/components/InputFormField/InputFormField.tsx
> +const InputFormField: React.FC<Props> = (props) => {
I think useField hook would be great here.
We can add error message right after Field component.
Reference: [Formik dock](https://formik.org/docs/tutorial#leveraging-react-context) (at the end).

2023-03-24 15:42 UTC, NikoraDmytro commented on client/src/components/InputFormField/InputFormField.tsx
> +const InputFormField: React.FC<Props> = (props) => {
Better not use React.FC<Props>.
Instead use one of this:
`const name = (props: Props) => {}`
`const name = (props: Props): JSX.Element => {}`

Reference: [Remove React.FC](https://github.com/facebook/create-react-app/pull/8177).

2023-03-24 15:42 UTC, NikoraDmytro commented on client/src/components/RegistrationForm/RegistrationForm.tsx
> +          {touched.email && errors.email && (
I think error elements can be added directly to InputFormField component.

2023-03-24 15:42 UTC, NikoraDmytro commented on client/src/components/RegistrationForm/RegistrationForm.tsx
> +import InputFormField from '../InputFormField/InputFormField';
No required (seriously, this isn't even a recommendation). 
You can add index.ts to InputFormField folder.
In index.ts use this code: 
`export { InputFormField } from "./InputFormField"`
Then you can use import like this: 
`import InputFormField from '../InputFormField'`

Reference: [folder components](https://medium.com/bootstart/you-should-be-using-folder-components-b30b7d165c39)

2023-03-24 15:51 UTC, NikoraDmytro commented
Also "Forgot password" button looks weird to me.
Something like this should be great.
![image](https://user-images.githubusercontent.com/63393400/227573926-b48fd226-2113-4c9b-a701-2f2361bede69.png)
![image](https://user-images.githubusercontent.com/63393400/227574147-8ba1574a-a462-4ca9-b9f5-d94b212401da.png)

2023-03-24 17:37 UTC, ira-bibik commented
![image](https://user-images.githubusercontent.com/114294333/227599789-e450422d-81d6-456d-ae6f-020f9679d877.png)

2023-03-25 00:36 UTC, NikoraDmytro approved these changes
Seems good to me.

2023-03-25 00:40 UTC, merged